version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  
  server:
    image: node:20-alpine
    container_name: backend_c
    working_dir: /app
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - "./server/:/app"
      
    depends_on:
      - mongodb
    
  client:
    image: node:20-alpine
    container_name: frontend_c
    working_dir: /src
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/src"
    depends_on:
      - server
    # Allows you to run container in detached mode.
    #stdin_open: true
    #tty: true
    #depends_on:
    #  - server
volumes:
  mongodb:
  mongodb_config:
  
