export const ACCOUNTLOADING = "ACCOUNTLOADING";

export const GETALLACCOUNTSSUCCESS = "GETALLACCOUNTSSUCCESS";

export const GET_ONE_ACCOUNT_SUCCESS = "GET_ONE_ACCOUNT_SUCCESS";

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const ACCOUNTFAILED = "ACCOUNTFAILED";
