export const COMPANYLOADING = "COMPANYLOADING";

export const GETALLCOMPANIESSUCCESS = "GETALLCOMPANIESSUCCESS";

export const COMPANYFAILED = "COMPANYFAILED";

export const ADDCOMPANYSUCCESS = "ADDCOMPANYSUCCESS";

export const DELETECOMPANYSUCCESS = "DELETECOMPANYSUCCESS";

export const APPLICATIONLOADING = "APPLICATIONLOADING";

export const ADDAPPLICATIONSUCCESS = "ADDAPPLICATIONSUCCESS";

export const GETALLAPPLICATIONSUCCESS = "GETALLAPPLICATIONSUCCESS";

export const APPLICATIONFAILED = "APPLICATIONFAILED";

export const EDITAPPLICATIONSUCCESS = "EDITAPPLICATIONSUCCESS";
