export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";

export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";

export const POST_NOTIFICATION_SUCCESS = "POST_NOTIFICATION_SUCCESS";

export const MARK_NOTIFICATION_AS_READ_SUCCESS =
  "MARK_NOTIFICATION_AS_READ_SUCCESS";

  export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";

export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED ";
