export const RAPPORTLOADING = "RAPPORTLOADING";

export const CREATEREPORTSUCCESS = "CREATEREPORTSUCCESS";

export const DOWNLOAD_REPORT_SUCCESS = "DOWNLOAD_REPORT_SUCCESS";

export const DOWNLOAD_REPORT_FAILED = "DOWNLOAD_REPORT_FAILED";

export const GETALLREPORTSSUCCESS = "GETALLREPORTSSUCCESS";

export const RAPPORTFAILED = "RAPPORTFAILED";

export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";

export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL";
